### ISSUE TITLE
Issue with streamCreated event not firing

### ISSUE THREAD

**Issue by rollsroyc3** [jwcao/opentok-titanium#2]
Hi, we have had this module setup and working for months but recently I cannot get it to connect on iOS or Android. We have done some initial debugging but have not found the reason. I am just wondering if you have had any issues with it as of late?

**Comment by jwcao** [comment]
We haven't had any issues with it for quite a while, and the version here on Github is what we're using. Since it started happening on both iOS and Android at the same time, I'm wondering if the issue may be on Opentok's side related to your account?

**Comment by rollsroyc3** [comment]
Thanks, I think we solved it. Issues with API keys.
