### ISSUE TITLE
Mute functionality

### ISSUE THREAD

**Issue by rollsroyc3** [jwcao/opentok-titanium#3]
Hi, I was wondering if it would be possible to build in mute functionality? We currently use this between clients and doctors and its a feature requested quite often.  I looked into appcelerator documentation and it does not seem that any mute functionality exists in the TiSDK. I can possibly look into building it myself but I was wondering if it would be better to build that as a separate module or part of this module.

Thanks

**Comment by jwcao** [comment]
Use the setPublishAudio method on the publisher proxy to mute your audio. There's a similar method on the subscriber proxy to mute the other person.

https://github.com/jwcao/opentok-titanium/blob/master/android/src/com/tokbox/ti/opentok/PublisherProxy.java#L69

https://github.com/jwcao/opentok-titanium/blob/master/android/src/com/tokbox/ti/opentok/SubscriberProxy.java#L47
