### ISSUE TITLE
Error building IOS module

### ISSUE THREAD

**Issue by ericpolkadoc** [jwcao/opentok-titanium#5]
Hi, 

Im new to building with python -- having an issue building the IOS module.

-- ive set my tokbox app key in the 2 required places
-- running the build.py script gives me

Traceback (most recent call last):
  File "/Directory/to/build.py", line 263, in <module>
    build_module(manifest,config)
  File "/Directory/to/build.py", line 174, in build_module
    from tools import ensure_dev_path
ImportError: No module named tools

Any help would be appreciated.

Thanks!

**Comment by jwcao** [comment]
I would try doing a Google search for the error you're getting. Make sure you have the Python tools installed, and that you're doing this on OSX.

**Comment by ericpolkadoc** [comment]
ok -- found the issue.  I am using the 5.0.2.GA SDK -- had to update my titanium.xcconfig to reflect the new file locations.

Thanks!
